FROM ubuntu:noble

# setup environment
WORKDIR /app
RUN mkdir /app/output

# install pipx 
RUN apt update && apt install pipx -y && rm -rf /var/lib/apt/lists/*
RUN pipx ensurepath

# install keymap-drawer
RUN pipx install keymap-drawer

# set user 
USER root

# copy over required files
COPY drawer/drawer_conf.yaml .
COPY drawer/generate.sh .
COPY config ./config

# create the SVG keymap drawing 
RUN chmod +x ./generate.sh
ENTRYPOINT [ "./generate.sh" ]