# only runs when changes to config are made
name: Firmware Build

on: 
  push:
    paths: ['config/**']
  pull_request:
    paths: ['config/**']
  workflow_dispatch:


jobs:
  build:
    name: Build Firmware
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
